#===========================================================================
# allowed DPIs
#===========================================================================
dpis:
  - 600
  - 254
  - 190
  - 127

#===========================================================================
# the allowed scales
#===========================================================================
scales:
  - 5000
  - 10000
  - 25000
  - 50000
  - 100000
  - 200000
  - 500000
  - 1000000
  - 2000000
  - 4000000
  - 40000000
  - 100000000
  - 140000000

formats:
  - pdf
  - png
  - jpeg

#===========================================================================
# the list of allowed hosts
#===========================================================================
hosts:
  - !localMatch
    dummy: true
 
  - !ipMatch
    host: 127.0.0.1
    # Allow to all hosts
    mask: 0.0.0.0
   
layouts:
  #===========================================================================
  Thumbnail:
    mainPage:
      rotation: false
      pageSize: LEGAL
      landscape: true
      backgroundPdf: '${configDir}/template-thumbnail.pdf'
      items:
        - !map
          spacingAfter: 0
          width: 1008
          height: 612
          absoluteX: 0
          absoluteY: 612
  #===========================================================================
  A4 portrait:
    mainPage:
      rotation: true
      pageSize: A4
#      backgroundPdf: '${configDir}/template.pdf'
      header:
        height: 50
        items:
          - !text
            font: Helvetica
            fontSize: 30
            align: right
  #            text: '${mapTitle}'
      items:
        - !columns
          absoluteX: 57 
          absoluteY: 780
          width: 350
          items:
            - !image
              maxHeight: 40
              maxWidth: 220
              url: '${configDir}/logo_GL.jpeg'
        - !columns
          config:
            borderWidth: 2 
            borderColor: black
          absoluteX:58
          absoluteY:707
          width: 480
          spacingAfter: 30
          items: 
            - !map
              width: 480
              height: 530
        - !columns
          absoluteX: 57
          absoluteY: 155
          width: 160
          items:
            - !scalebar
              align: left
              maxSize: 160
              type: 'bar sub'
              intervals: 5
              units: km
        - !columns
          absoluteX: 515
          absoluteY: 210
          width: 30
          items:
            - !image
              maxWidth: 30
              maxHeight: 30
              url: 'file://${configDir}/Arrow_North_CFCF.svg'
              rotation: '${rotation}'
        - !columns
          absoluteX: 57
          absoluteY: 120
          width: 300
          items:
            - !text
                text: '${comment}'
        - !columns
          absoluteX: 57
          absoluteY: 50
          width: 300
          items:
            - !text
                text: '${now yyyy} Catalogue du Grand Lyon'  
                fontEncoding: Cp1252
                fontSize: 10
  
  #===========================================================================
  A4 paysage:
  #===========================================================================
    mainPage:
      rotation: true
      pageSize: 842 595
      header:
        height: 50
        items:
          - !text
            font: Helvetica
            fontSize: 30
            align: right
#            text: '${mapTitle}'
      items:
        - !columns
          absoluteX: 57 
          absoluteY: 570
          width: 350
          items:
            - !image
              maxHeight: 40
              maxWidth: 220
              url: '${configDir}/logo_GL.jpeg' 
        - !columns
          config:
            borderWidth: 2 
            borderColor: black
          absoluteX:58
          absoluteY:520
          width: 727
          spacingAfter: 30
          items: 
            - !map
              width: 727
              height: 380
        - !columns
          absoluteX: 57
          absoluteY: 130
          width: 160
          items:
            - !scalebar
              align: left
              maxSize: 160
              type: 'bar sub'
              intervals: 5
              units: km
        - !columns
          absoluteX: 730
          absoluteY: 190
          width: 30
          items:
            - !image
              maxWidth: 30
              maxHeight: 30
              url: 'file://${configDir}/Arrow_North_CFCF.svg'
              rotation: '${rotation}'
        - !columns
          absoluteX: 57
          absoluteY: 110
          width: 500
          items:
            - !text
                text: '${comment}'
        - !columns
          absoluteX: 57
          absoluteY: 40
          width: 300
          items:
            - !text
                text: '${now yyyy} Catalogue du Grand Lyon'
                fontEncoding: Cp1252
                fontSize: 10